name: "Pico Software"

on:
  push:
    paths:
      - '.github/workflows/pico-build.yml'
      - 'PMod_LED/pico/*'
  pull_request:
    paths:
      - '.github/workflows/pico-build.yml'
      - 'PMod_LED/pico/*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

 Build-Software:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: project

      - name: Checkout Pico SDK
        uses: actions/checkout@v2
        with:
          repository: raspberrypi/pico-sdk
          path: pico-sdk
          submodules: true

      - name: Install deps
        run: |
          sudo apt update && sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib
      - name: Make directory
        run: |
          mkdir project/Pico/build
      - name: Build
        working-directory: project/Pico/build
        shell: bash
        run: |
          PICO_SDK_PATH=../../pico-sdk cmake ..
          make
      - name: Retrieve results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: RP_Pico_Files
          path: |
            project/Pico/build/*.uf2
          if-no-files-found: warn
